apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: foxtown
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
